favicon: null
name: SpotOn Bilpleje
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
purpose: []
color:
  saturation: 0.9794822426047176
  brandStrength: 1
  lightness: 0.5850728221703321
  brandColors:
    - '#5C1527'
    - '#FF2744'
    - '#FFFFFF'
    - '#B36E5E'
    - '#6D9CE4'
  rhythmicContrast: 0.1299849157221615
typography_spectrum: 0.64761
layout_spectrum: 1
analytics:
  twitter: null
  google: null
  facebook: null
cta:
  bucket: null
  version: null
  domain: null
