name: SpotOn Bilpleje
favicon: null
layout_spectrum: 0.51239
typography_spectrum: 0.23615694209001958
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.755939077353105
  lightness: 0.5850728221703321
  saturation: 0.9794822426047176
  rhythmicContrast: 0.12998491572216153
purpose: []
